### ISSUE TITLE
Week 03 Day 2 - Cloudy with a chance of Syntax Error - 

### ISSUE THREAD

**Issue by mdewey** [DRibeiro1124/Assignments#10]
Using a popular weather API, Create a web site that allows a user to search for a location and gets that places weather.

## Objectives

- Practice working with an API
- Practice working with data that was structure by a third party

## Requirements

- Using `openweathermap.org`, create a simple UI that allows a user to search for the current weather by zip code or city

### Explorer Mode

- [x] Create a simple HTML page that has a text box and a search `button`
- [x] Allow the user to type in a place, click the search button, and , using `openweathermap.org`, get the current weather for that location
- [x] Display the weather to user by adding elements to the DOM.
- [x] Allow the user to search by zip or city name.

## Adventure Mode

- [ ] Using the HTML5 Geolocation API, search for the users current location when page loads
- [ ] Store the Users last search and pull it and search for the value on page load
- [ ] remove the need for teh search button and search when the user stops typeing. HINT: use setTimeout and the change event. to track when the user stops typing.

## Epic Mode

- [ ] Add a type a head using Google Places API
- [ ] Head back to blackjack and use [https://deckofcardsapi.com/](https://deckofcardsapi.com/) as your API

**Comment by DRibeiro1124** [comment]
https://github.com/DRibeiro1124/weather-api

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/xUA7aSNjOfQS4i4s2k/200w_d.gif)
