### ISSUE TITLE
Final Project 1 - It starts with a plan. - 

### ISSUE THREAD

**Issue by mdewey** [DRibeiro1124/Assignments#27]
We are starting the final stretch of the cohort. This means we are starting to focus on our final projects. 

When we go to start a new project. The first step is create an elevator pitch. This is a short description that describes what your final project is doing. This should be simliar to what you said last week for lab.

The second step is to always plan out what we are doing. These early plans often take the shape of wire frames. This means that our first task for the capstone projects is create our wire frames.

The elevator pitch wire frames should be treated as a detailed road map. When these are created, these should be treated as law; it can be changed, but must be changed with purpose.

## Objectives

* Finalize the idea for your capstone
* Create wire frames for your capstone project

## Requirements

* Using your favorite way to create wire frames (paper, whiteboard, website), create all the pages for your site no matter how simple the pages are. 
* Create a new repository for your capstone project

### Explorer Mode, Due Friday 9/7

* [x] Create the elevator pitch for your final projects. 
* [ ] Place this in the `README.md` of your capstone project repository 

### Explorer Mode, Due Monday 9/10
* [x] Create a wire frame for each page in your page you capstone. 
* [ ] Place these wire frames in an `.idea` folder of your capstone project repository.

## Additional Resources

- [Adobe XD](https://www.adobe.com/products/xd.html), _free_ software from Adobe for designing and prototyping website and mobile apps.
- [Moqups](https://moqups.com/), a web-based tool for collaborating on wireframes, mockups and prototypes.

**Comment by DRibeiro1124** [comment]
![img_1817 2](https://user-images.githubusercontent.com/29757180/45295780-e77fae00-b4cd-11e8-80e2-28e9dd8c2c13.jpg)
![img_1818 2](https://user-images.githubusercontent.com/29757180/45295781-e77fae00-b4cd-11e8-8110-48f19f486ab9.jpg)
![img_1819 2](https://user-images.githubusercontent.com/29757180/45295782-e77fae00-b4cd-11e8-9212-02d5a273284a.jpg)

I'm making a change to my project.  Instead on focusing on stadiums, I'm going to make the project on the English Premier League. 


I'm creating a dynamic webpage about the English Premier League.  I'm going to implement what I learn in Ruby on Rails backend to create some sort of database that will compile data from the 2018-19 season.  Each team page will have current stats in which I'll be using Ruby on Rails to keep track.  In each individual team page, I'm going to be calling an API (football-api.com) and the users will be able to pull data from past seasons as well other information on certain teams.  If I'm able to get everything done correctly I will then try and use google map api to add location for each team as well.

**Comment by DRibeiro1124** [comment]
https://github.com/DRibeiro1124/English-Premier-League/tree/master

**Comment by mdewey** [comment]
Great start. I would love to see more details in the wireframes
