### ISSUE TITLE
Week 02 Day 1 - Scoreboard - 

### ISSUE THREAD

**Issue by mdewey** [DRibeiro1124/Assignments#5]
# Score Board

For this assignment you will creating a simple interactive score board for your favorite sport.

A User should be able to update a score and the teams playing.

### Explorer Mode

Should resemble this:
![markup](https://raw.githubusercontent.com/suncoast-devs/handbook/master/content/curriculum/fundamentals/javascript/assignments/assets/scoreboard-day-1.buttons.PNG)

- [ ] implement the basic HTML
- [ ] implement the basic formating. Do not worry about styling (colors and fonts and the like)
- [ ] add click events to the `update` buttons to update the corresponding values on the page. The score buttons should adjust the current score by a "hard coded" value

### Adventure Mode

- [ ] Complete Explorer Mode
- [ ] Implement a Quarter/Period Tracker that would be appropriate for the sport
- [ ] Add some custom CSS to make it more colorful. Have fun with it
- [ ] Make the layout responsive

### Epic Mode

- [ ] Add a Timer that counts down automatically and updates the period/quarter appropriately
- [ ] Save/load the information to local storage
- [ ] Add CSS to the winning teams score to indicate who is currently winning
- [ ] add anything else that your sport would have on its score board (fouls, sacks, shots on goal, etc);
- [ ] Improve the UX to help making score keeping by your sport easier

**Comment by DRibeiro1124** [comment]
https://github.com/DRibeiro1124/scoreboard
Took me longer than I wanted to and after staying late with Gus I think I'm finally getting the grasp of html and the flex-box.  It's getting late and I'm going to get some sleep and work on this confusing JS when I get to school at 6:30 am

**Comment by mdewey** [comment]
This will be marked incomplete until you get the JavaScript filled in.

**Comment by DRibeiro1124** [comment]
https://github.com/DRibeiro1124/scoreboard
Sorry Mark, I re-did the whole thing today and I'm still really struggling with JS.  I got Gus to help me with the JS and I'm getting a better grasp of it but I'm still really far behind everyone else in class.

**Comment by DRibeiro1124** [comment]
https://github.com/DRibeiro1124/scoreboard

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/7JsT71QjexH1JSTYJA/200w_d.gif)
